env:
  global:
    - COMPOSER_MEMORY_LIMIT=-1
    - XDEBUG_MODE=coverage

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer install
  - vendor/bin/phpunit
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.3" ]]; then vendor/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN; fi
